# Use Python 3.10 image
FROM python:3.10-slim

# Set /app as working directory
WORKDIR /app

# Copy Python modules requirements
COPY requirements.txt .

# Install requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Cron app
COPY api/ ./

# Set args
ARG gcp_credentials

# Set environment variables
ENV GOOGLE_APPLICATION_CREDENTIALS=$gcp_credentials

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
