version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local.api
    ports:
      - "8000:8000"

  cron:
    build:
      context: .
      dockerfile: Dockerfile.local.cron
